# Enable this to get bug fixes and support asap
auto-update: false

worlds:

  # The name of your world that is Earth.
  # This should be the name main world where people work on stuff and make bases.
  earth-name: world

aliens:

  # How often aliens tick in Minecraft ticks - there are 20 ticks in 1 second
  tick-interval: 2

  # Maximum number of aliens per player per world
  max-per-player: 32

  # Chance for a Leech to eat an item
  leech-eat-chance: 50

rockets:
  
  # Messages while rocket is launching. Must have at least 4
  launch-msgs: 
    - 正在丢弃降落伞
    - 正在装填小吃箱
    - 正在校准行星
    - 正在点亮太阳
    - 正在添加有趣的发射提示
    - 正在感谢TheBusyBiscuit(粘液科技作者)
    - 正在模拟登陆月球
    - 正在迈出一小步
    - 正在迈出人类的一大步
    - 不回家了

other:
  # The range that the automatic door checks for players
  auto-door-range: 2
  # Blocks prohibited to be used by the automatic door
  auto-door-banned-types:
    - BEDROCK
    - CAKE
    - BARRIER
    - COMMAND_BLOCK
    - END_PORTAL
    - STRUCTURE_BLOCK
